2021-02-06 11:57:32,440 ERROR 16044 [-/127.0.0.1/-/200ms POST /add] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'heihei.users' doesn't exist
    at Query.Sequence._packetToError (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    --------------------
    at Pool.query (D:\没头发的不归路\egg\egg-first\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at D:\没头发的不归路\egg\egg-first\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\没头发的不归路\egg\egg-first\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (D:\没头发的不归路\egg\egg-first\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (D:\没头发的不归路\egg\egg-first\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (D:\没头发的不归路\egg\egg-first\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\没头发的不归路\egg\egg-first\node_modules\_co@4.6.0@co\index.js:65:19)
    at D:\没头发的不归路\egg\egg-first\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `users`(`id`, `name`, `time`) VALUES('4', '哈哈', '')
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'heihei.users' doesn't exist"
sqlState: "42S02"
index: 0
sql: "INSERT INTO `users`(`id`, `name`, `time`) VALUES('4', '哈哈', '')"
name: "ER_NO_SUCH_TABLEError"
pid: 16044
hostname: DESKTOP-SB2DNI0

2021-02-06 14:18:38,545 ERROR 3120 nodejs.ClusterClientNoResponseError: client no response in 5779073ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (D:\没头发的不归路\egg\egg-first\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 3120
hostname: DESKTOP-SB2DNI0

